<?php
class Project{
	public $project_name;
	public $year;
	public function __construct($project_name, $year){
		$this->project_name = $project_name;
		$this->year = $year;
	}
}
class Contact{
	public $contact_id;
	public $nickname;
	public $fullname;
	public $bday;
	public $gender;
	public $addr;
	public $email;
	public $imageurl;
	public $projects = [];
	public function __construct($contact_id, $nickname, $fullname, $bday, $gender, $addr, $email, $imageurl,$projects) {
		$this->contact_id = $contact_id;
		$this->nickname = $nickname;
		$this->fullname = $fullname;
		$this->bday = $bday;
		$this->gender = $gender;;
		$this->addr = $addr;
		$this->email = $email;
		$this->imageurl = $imageurl;
		$this->projects = $projects;
	}
}
$contacts = [new Contact("C001","kate", "kathryn bailey beckinsale", "26-jul-1973", "female", "#23 underworld drive", "kate@lycans.net", "images/001.jpg",
[new Project("Children in Need","2003"),
new Project("Friday Night with Jonathan Ross","2003"),
new Project("Last Call with Carson Daly","2003"),
new Project("The Daily Show","2001-2003"),
new Project("Pearl Harbor: Production Diary","2002"),
new Project("2002 MTV Movie Awards","2002"),
new Project("8th Annual Screen Actors Guild Awards","2002"),
new Project("On the Set: Serendipity","2001"),
new Project("The Big Breakfast","2001"),
new Project("So Graham Norton","2001"),
new Project("Journey to the Screen: The Making of 'Pearl Harbor'","2001"),
new Project("The Rosie O'Donnell Show","2001"),
new Project("Mundo VIP","2001"),
new Project("The Unforgettable Richard Beckinsale","2000"),
new Project("HBO First Look","1999"),
new Project("Ladies & Gentlemen: The Best of George Michael","1999"),
new Project("Un siecle d'ecrivains","1998"),
new Project("Cinema 3","1993"),
new Project("This Is Your Life","1977"),
new Project("Entertainment Tonight","2009-2020"),
new Project("Good Morning Britain","2019"),
new Project("Extra with Billy Bush","2015-2019"),
new Project("Untouchable","2019"),
new Project("Access Hollywood","2017"),
new Project("Sky World News","2017"),
new Project("Superheroes Who Have Been Nude","2016"),
new Project("The Insider","2015"),
new Project("You Saw Them Here First","2013"),
new Project("Almost Famous II","2009"),
new Project("MythBusters","2006"),
new Project("VH1 News Presents","2006"),
new Project("101 Sexiest Celebrity Bodies","2005"),
new Project("Coming Attractions","2003")]),
			new Contact("C002","bob", "robert john downey jr", "04-apr-1965", "male", "45 steel blvd", "jstark@ironman.net", "images/002.jpg", [new Project("Untitled John Brinkley Biopic",null),
new Project("Sherlock Holmes 3","2021"),
new Project("All-Star Weekend",null),
new Project("Black Widow","2020"),
new Project("Dolittle","2020"),
new Project("Dolittle - Auditions","2019"),
new Project("Avengers: Endgame","2019"),
new Project("Avengers: Infinity War","2018"),
new Project("Spider-Man: Homecoming","2017"),
new Project("Spider-Man: Homecoming, NBA Finals: Watch the Game","2017"),
new Project("Captain America: Civil War","2016"),
new Project("Avengers: Age of Ultron","2015"),
new Project("The Judge","2014"),
new Project("Chef","2014"),
new Project("Iron Man 3","2013"),
new Project("The Avengers","2012"),
new Project("Sherlock Holmes: A Game of Shadows","2011"),
new Project("Due Date","2010"),
new Project("Love & Distrust","2010"),
new Project("Iron Man 2","2010"),
new Project("Sherlock Holmes","2009"),
new Project("The Soloist","2009"),
new Project("Tropic Thunder: Rain of Madness","2008"),
new Project("Tropic Thunder","2008"),
new Project("The Incredible Hulk","2008"),
new Project("Iron Man","2008"),
new Project("Charlie Bartlett","2007"),
new Project("Lucky You","2007"),
new Project("Vanity Fair: Killers Kill, Dead Men Die","2007"),
new Project("Zodiac","2007"),
new Project("Fur: An Imaginary Portrait of Diane Arbus","2006"),
new Project("A Scanner Darkly","2006"),
new Project("The Shaggy Dog","2006"),
new Project("A Guide to Recognizing Your Saints","2006"),
new Project("Family Guy","2005"),
new Project("Good Night, and Good Luck.","2005"),
new Project("Kiss Kiss Bang Bang","2005"),
new Project("Game 6","2005"),
new Project("The Route V50","2004"),
new Project("Eros","2004"),
new Project("Gothika","2003"),
new Project("Whatever We Do","2003"),
new Project("The Singing Detective","2003"),
new Project("Ally McBeal","2000-2002"),
new Project("Lethargy","2002"),
new Project("Bob Dylan: Things Have Changed","2000"),
new Project("Auto Motives","2000"),
new Project("Wonder Boys","2000"),
new Project("Black & White","1999/I"),
new Project("Bowfinger","1999"),
new Project("Friends & Lovers","1999"),
new Project("In Dreams","1999"),
new Project("U.S. Marshals","1998"),
new Project("The Gingerbread Man","1998"),
new Project("Hugo Pool","1997"),
new Project("Two Girls and a Guy","1997"),
new Project("One Night Stand","1997"),
new Project("Danger Zone","1996"),
new Project("Restoration","1995"),
new Project("Mr. Willowby's Christmas Tree","1995"),
new Project("Home for the Holidays","1995"),
new Project("Richard III","1995"),
new Project("Only You","1994"),
new Project("Natural Born Killers","1994"),
new Project("Hail Caesar","1994"),
new Project("Short Cuts","1993"),
new Project("Heart and Souls","1993"),
new Project("Chaplin","1992"),
new Project("Soapdish","1991"),
new Project("Too Much Sun","1990"),
new Project("Air America","1990"),
new Project("Chances Are","1989"),
new Project("True Believer","1989"),
new Project("That's Adequate","1989"),
new Project("1969","1988"),
new Project("Rented Lips","1988"),
new Project("Johnny Be Good","1988"),
new Project("Less Than Zero","1987"),
new Project("The Pick-up Artist","1987"),
new Project("America","1986"),
new Project("Back to School","1986"),
new Project("Saturday Night Live","1985-1986"),
new Project("Deadwait","1985"),
new Project("Mussolini: The Untold Story","1985"),
new Project("Weird Science","1985"),
new Project("Girls Just Want to Have Fun","1985"),
new Project("Tuff Turf","1985"),
new Project("Firstborn","1984"),
new Project("Baby It's You","1983"),
new Project("Up the Academy","1980"),
new Project("Greaser's Palace","1972"),
new Project("Pound","1970"),
new Project("A Head Full of Ghosts",null),
new Project("Untitled John Brinkley Biopic",null),
new Project("Sweet Tooth",null),
new Project("Constance",null),
new Project("Perry Mason","2020"),
new Project("The Age of A.I.","2019-2020"),
new Project("Dolittle","2020"),
new Project("Playing It Forward: Imagine Dragons","2014"),
new Project("The Judge","2014"),
new Project("Playing It Forward: John Legend","2013"),
new Project("A Guide to Recognizing Your Saints","2006"),
new Project("The Tonight Show Starring Jimmy Fallon","2014-2019"),
new Project("Just Go with It","2011"),
new Project("Kiss Kiss Bang Bang","2005"),
new Project("The Singing Detective","2003"),
new Project("Ally McBeal","2000-2001"),
new Project("Friends & Lovers","1999"),
new Project("Two Girls and a Guy","1997"),
new Project("Heart and Souls","1993"),
new Project("Too Much Sun","1990"),
new Project("The Last Party","1993"),
new Project("Singularity",null),
new Project("Dizzy Pursuit","2018"),
new Project("Marvel Studios: Assembling a Universe","2014"),
new Project("International Relations Theory Illustrated #1 Realism","2012"),
new Project("A Backyard Story","2010"),
new Project("Tropic Thunder: Rain of Madness","2008"),
new Project("Chaos Rising: The Storm Around 'Natural Born Killers'","2001"),
new Project("Martini Ranch: Reach","1988"),
new Project("The Graham Norton Show","2009-2020"),
new Project("C a vous","2020"),
new Project("Celebrity Page","2017-2020"),
new Project("Entertainment Tonight","2007-2020"),
new Project("The Age of A.I.","2019-2020"),
new Project("The Joe Rogan Experience","2020"),
new Project("The Tonight Show Starring Jimmy Fallon","2014-2020"),
new Project("Today","2020"),
new Project("The Ellen DeGeneres Show","2003-2020"),
new Project("Access Hollywood","2008-2020"),
new Project("Extra with Billy Bush","2003-2020"),
new Project("Ellen's Greatest Night of Giveaways","2019"),
new Project("The E! People's Choice Awards","2019"),
new Project("Teen Choice Awards 2019","2019"),
new Project("Off Camera with Sam Jones","2014-2019"),
new Project("2019 MTV Movie & TV Awards","2019"),
new Project("WGN Morning News","2019"),
new Project("The Chef Show","2019"),
new Project("Red Carpet Report","2016-2019"),
new Project("Marvel Studios' Avengers: Endgame LIVE Red Carpet World Premiere","2019"),
new Project("Entertainment Tonight Canada","2019"),
new Project("Good Morning America","2014-2019"),
new Project("Jimmy Kimmel Live!","2008-2019"),
new Project("Laugh Factory","2019"),
new Project("Marvel Studios: The First Ten Years - Connecting the Universe","2018"),
new Project("Marvel Studios: The First Ten Years - The Evolution of Heroes","2018"),
new Project("Spider-Man: Homecoming, Jon Watts, Head of the Class","2017"),
new Project("Spider-Man: Homecoming, searching for Spider-Man","2017"),
new Project("A Fan's Guide to Spider-Man: Homecoming","2017"),
new Project("The 43rd Annual People's Choice Awards","2017"),
new Project("Captain America: The Road to Civil War","2016"),
new Project("Iron Man: The Road to Civil War","2016"),
new Project("United We Stand, Divided We Fall: The Making of 'Captain America: Civil War'","2016"),
new Project("Made in Hollywood","2010-2016"),
new Project("Live! with Kelly","2005-2016"),
new Project("Last Week","2016"),
new Project("Robert Downey Jr.'s Biggest Big Announcement of All Time","2016"),
new Project("2016 MTV Movie Awards","2016"),
new Project("Nickelodeon Kids' Choice Awards 2016","2016"),
new Project("ABFF Awards a Celebration of Hollywood","2016"),
new Project("Movie Surfers","2016"),
new Project("Avengers: Age of Ultron - Bookending the Action","2015"),
new Project("From Here to Infinity: Phases 2 & 3 of the M.C.U.","2015"),
new Project("Phase 2 Tag Scenes: A Making of the Marvel Cinematic Universe Phase Two","2015"),
new Project("The British Academy Britannia Awards","2015"),
new Project("Avengers: Age of Ultron - From the Inside Out: Making of Avengers - Age of Ultron","2015"),
new Project("CollegeHumor Originals","2015"),
new Project("Late Show with David Letterman","1995-2015"),
new Project("The Insider","2014-2015"),
new Project("2015 MTV Movie Awards","2015"),
new Project("Explosiv - Das Magazin","2015"),
new Project("The EE British Academy Film Awards","2015"),
new Project("72nd Golden Globe Awards","2015"),
new Project("The 41st Annual People's Choice Awards","2015"),
new Project("Hollywood Sessions","2014"),
new Project("Hollywood Film Awards","2014"),
new Project("BAFTA Britannia Awards Special 2014","2014"),
new Project("CBS This Morning","2014"),
new Project("Late Night with Seth Meyers","2014"),
new Project("The Judge: Inside the Judge","2014"),
new Project("Stand Up to Cancer","2014"),
new Project("I Am Steve McQueen","2014"),
new Project("Howard Stern Birthday Bash","2014"),
new Project("Nickelodeon Kids Choice Awards 2014","2014"),
new Project("Marvel Studios: Assembling a Universe","2014"),
new Project("19th Annual Critics' Choice Movie Awards","2014"),
new Project("71st Golden Globe Awards","2014"),
new Project("The 40th Annual People's Choice Awards","2014"),
new Project("Iron Man 3: Sky Movies Special","2013"),
new Project("Superheroes: From Page to Screen","2013"),
new Project("Iron Man 3 Unmasked","2013"),
new Project("Iron Man 3: Advancing the Tech","2013"),
new Project("Taff","2008-2013"),
new Project("The Daily Show","2013"),
new Project("Weekend Ticket","2013"),
new Project("Vivir de cine","2013"),
new Project("The Tonight Show with Jay Leno","1993-2013"),
new Project("Daybreak","2011-2013"),
new Project("S.H.I.E.L.D.: And Then Shawarma After","2013"),
new Project("Celebrity Style Story","2013"),
new Project("The Oscars","2013"),
new Project("70th Golden Globe Awards","2013"),
new Project("The 39th Annual People's Choice Awards","2013"),
new Project("Electric Playground","2012"),
new Project("The American Cinematheque Tribute to Ben Stiller","2012"),
new Project("Building the Dream: Assembling the Avengers","2012"),
new Project("The Avengers: Assembling the Ultimate Team","2012"),
new Project("Sherlock Holmes and Dr. Watson: A Perfect Chemistry","2012"),
new Project("Fantastic","2012"),
new Project("Finding Your Roots with Henry Louis Gates, Jr.","2012"),
new Project("VIP zpravy","2012"),
new Project("The Avengers Assemble Premiere","2012"),
new Project("YourGeekNews.com","2012"),
new Project("Nickelodeon Kids' Choice Awards 2012","2012"),
new Project("The 84th Annual Academy Awards","2012"),
new Project("The 69th Annual Golden Globe Awards","2012"),
new Project("Janela Indiscreta","2010-2012"),
new Project("The 7PM Project","2010-2012"),
new Project("The Big Picture","2012"),
new Project("The American Cinematheque Tribute to Robert Downey Jr","2011"),
new Project("Up Close with Carrie Keagan","2007-2011"),
new Project("The BAFTA Britannia Awards","2011"),
new Project("Scream Awards 2011","2011"),
new Project("Close Up","2011"),
new Project("Marvel LIVE! World Premiere of Captain America: The First Avenger","2011"),
new Project("The 83rd Annual Academy Awards","2011"),
new Project("The 68th Annual Golden Globe Awards","2011"),
new Project("What The","2011"),
new Project("Mad Mel: The Rise and Fall of a Hollywood Icon","2010"),
new Project("Iron Man 2: Creating Stark Expo","2010"),
new Project("Iron Man 2: Practical Meets Digital","2010"),
new Project("Ultimate Iron Man","2010"),
new Project("Mark at the Movies","2010"),
new Project("The Late Late Show with Craig Ferguson","2008-2010"),
new Project("Dias de cine","2010"),
new Project("Guys Choice","2010"),
new Project("Friday Night with Jonathan Ross","2005-2010"),
new Project("Drawbridges & Dollies: Designing a Late Victorian London","2010"),
new Project("Elementary English: Perfecting Sherlock's Accent","2010"),
new Project("Sherlock Holmes: Ba-ritsu, A Tutorial","2010"),
new Project("Sherlock Holmes: Not a Deerstalker Cap in Sight","2010"),
new Project("Sherlock Holmes: Powers of Observation & Deduction","2010"),
new Project("Sherlock Holmes: Reinvented","2010"),
new Project("Sherlock Holmes: The One That Got Away","2010"),
new Project("Nickelodeon Kids' Choice Awards 2010","2010"),
new Project("The 82nd Annual Academy Awards","2010"),
new Project("The 52nd Annual Grammy Awards","2010"),
new Project("Cinema 3","2010"),
new Project("The 67th Annual Golden Globe Awards","2010"),
new Project("2009 Golden Globe Awards Red Carpet Special","2009"),
new Project("Live from Studio Five","2009"),
new Project("Xpose","2009"),
new Project("The Movie Loft","2008-2009"),
new Project("Spike's Guys Choice","2009"),
new Project("Star Movies: Live from the Red Carpet","2009"),
new Project("The 81st Annual Academy Awards","2009"),
new Project("This Morning","2005-2009"),
new Project("The 66th Annual Golden Globe Awards","2009"),
new Project("Biography","2004-2008"),
new Project("MTV Movie Awards: Tropic Thunder","2008"),
new Project("The Cast of 'Tropic Thunder'","2008"),
new Project("Tropic Thunder: Before the Thunder","2008"),
new Project("Tropic Thunder: Designing the Thunder","2008"),
new Project("Tropic Thunder: Full Mags","2008"),
new Project("I Am 'Iron Man'","2008"),
new Project("Iron Man: The Actor's Process","2008"),
new Project("Eigo de shabera-night","2008"),
new Project("Resumen - 56 Festival internacional de cine de San Sebastian","2008"),
new Project("Animal House: The Inside Story","2008"),
new Project("HBO First Look","2006-2008"),
new Project("AFI Life Achievement Award: A Tribute to Warren Beatty","2008"),
new Project("Spike Guys Choice","2008"),
new Project("Starz Inside: Comic Books Unbound","2008"),
new Project("2008 MTV Movie Awards","2008"),
new Project("American Idol","2008"),
new Project("The View","2005-2008"),
new Project("Exterieur jour","2008"),
new Project("Getaway","2008"),
new Project("Zodiac Deciphered","2008"),
new Project("The Modern Warrior","2007"),
new Project("This Is Zodiac","2007"),
new Project("Out of Control: 10 Celebrity Rehabs Exposed","2007"),
new Project("Payback","2007"),
new Project("HypaSpace","2007"),
new Project("The 79th Annual Academy Awards","2007"),
new Project("Film Independent's 2007 Spirit Awards","2007"),
new Project("One Summer in Austin: The Story of Filming 'A Scanner Darkly'","2006"),
new Project("The Weight of the Line: Animation Tales","2006"),
new Project("American Masters","2006"),
new Project("Inside the Actors Studio","2006"),
new Project("The 4th Annual TV Land Awards","2006"),
new Project("The Reichen Show","2006"),
new Project("Corazon de...","2005-2006"),
new Project("Shootout","2004-2006"),
new Project("GMTV","2005"),
new Project("Late Night with Conan O'Brien","2005"),
new Project("Film 2017","2005"),
new Project("The Showbiz Show with David Spade","2005"),
new Project("Larry King Live","2005"),
new Project("El Magacine","2005"),
new Project("Hubert Selby Jr: It/ll Be Better Tomorrow","2005"),
new Project("The New Paul O'Grady Show","2005"),
new Project("Breakfast","2005"),
new Project("The Outsider","2005"),
new Project("Last Call with Carson Daly","2005"),
new Project("Tsunami Aid: A Concert of Hope","2005"),
new Project("Tangled Up in Blue","2004"),
new Project("The Kennedy Center Honors: A Celebration of the Performing Arts","2004"),
new Project("The Art Show","2004"),
new Project("The Oprah Winfrey Show","2004"),
new Project("Gothika: Painting with Fire","2004"),
new Project("On the Set of 'Gothika'","2004"),
new Project("Between the Lines","2004"),
new Project("Punk'd","2003"),
new Project("Movie House","2003"),
new Project("The Frank Skinner Show","2003"),
new Project("Richard & Judy","2003"),
new Project("The Wayne Brady Show","2003"),
new Project("Charlie Rose","1995-2003"),
new Project("Charlie: The Life and Art of Charles Chaplin","2003"),
new Project("Hollywood Celebrates Denzel Washington: An American Cinematheque Tribute","2003"),
new Project("The 59th Annual Golden Globe Awards","2002"),
new Project("Elton John: I Want Love","2001"),
new Project("Anatomy of a Scene","2001"),
new Project("Last Party 2000","2001"),
new Project("7th Annual Screen Actors Guild Awards","2001"),
new Project("3rd Annual TV Guide Awards","2001"),
new Project("The 58th Annual Golden Globe Awards","2001"),
new Project("Chaos Rising: The Storm Around 'Natural Born Killers'","2001"),
new Project("1998 MTV Movie Awards","1998"),
new Project("Saturday Night Live","1986-1996"),
new Project("Kennedy Center's 25th Anniversary","1996"),
new Project("Maury","1996"),
new Project("Howard Stern","1995"),
new Project("1995 MTV Movie Awards","1995"),
new Project("A Century of Cinema","1994"),
new Project("The 1994 Billboard Music Awards","1994"),
new Project("Luck, Trust & Ketchup: Robert Altman in Carver Country","1993"),
new Project("Rock the Vote","1993"),
new Project("The Last Party","1993"),
new Project("The 65th Annual Academy Awards","1993"),
new Project("The 50th Annual Golden Globe Awards","1993"),
new Project("The South Bank Show","1992"),
new Project("1992 MTV Movie Awards","1992"),
new Project("The 43rd Annual Writers Guild Awards","1991"),
new Project("1990 MTV Video Music Awards","1990"),
new Project("Late Night with David Letterman","1990"),
new Project("The 61st Annual Academy Awards","1989"),
new Project("The Arsenio Hall Show","1989"),
new Project("Get Out the Vote","1988"),
new Project("The Starlight Annual Foundation Benefit","1988"),
new Project("1988 MTV Video Music Awards","1988"),
new Project("Dear America: Letters Home from Vietnam","1987"),
new Project("Two Tons of Turquoise to Taos Tonight","1975"),
new Project("Entertainment Tonight","2014-2020"),
new Project("Celebrating Marvel's Stan Lee","2019/II"),
new Project("L'Histoire nous le dira","2019"),
new Project("Entertainment Tonight Canada","2019"),
new Project("In Greene","2019"),
new Project("Celebrity Page","2017-2019"),
new Project("Hoy nos toca","2018"),
new Project("#TeamG1, la quotidienne","2018"),
new Project("The Zen Diaries of Garry Shandling","2018"),
new Project("Chelsea","2017"),
new Project("The Demonisation of the Elderly and the Exaltation of the Young","2017"),
new Project("La petite histoire des super-heros","2017"),
new Project("Extra with Billy Bush","2014-2017"),
new Project("TIME Presents: Celebrities on Trial","2017"),
new Project("L'antre du Mea","2016"),
new Project("Weekend Sunrise","2016"),
new Project("L'IA et Mathieu","2016"),
new Project("Taff","2016"),
new Project("IN101M","2016"),
new Project("Nostalgia Critic","2016"),
new Project("Lego Marvel's Avengers","2016"),
new Project("Inside Edition","2015"),
new Project("As I AM: The Life and Times of DJ AM","2015"),
new Project("Canada A.M.","2006-2015"),
new Project("Retro Report","2014"),
new Project("Live! with Kelly","2013"),
new Project("The Frame","2013"),
new Project("Chelsea Lately","2013"),
new Project("Movie Guide","2013"),
new Project("Biography","2007-2012"),
new Project("Too Young to Die","2012"),
new Project("Welcome to the Basement","2012"),
new Project("The Graham Norton Show","2011"),
new Project("Marvel One-Shot: The Consultant","2011"),
new Project("Road to 'The Avengers'","2011"),
new Project("Troldspejlet","2010"),
new Project("Richard Roeper & the Movies","2010"),
new Project("Never Sleep Again: The Elm Street Legacy","2010"),
new Project("Live from Studio Five","2010"),
new Project("Almost Famous III","2010"),
new Project("Sky News: Sunrise","2009"),
new Project("WWE Raw","2009"),
new Project("VH1 News Presents","2008"),
new Project("19/20","2008"),
new Project("City Confidential","2007"),
new Project("Saturday Night Live in the '80s: Lost & Found","2005"),
new Project("El Magacine","2005"),
new Project("101 Most Shocking Moments in Entertainment","2003"),
new Project("Showboy","2002"),
new Project("Ally McBeal","2001-2002"),
new Project("E! True Hollywood Story","2002"),
new Project("Why Robert?","2001")]),
			new Contact("C003","jessica", "jessica claire biel", "03-mar-1982", "female", "27 texas avenue", "jbiel@yahoo.com", "images/003.jpg", [new Project("Limetown","2019"),
new Project("Pete the Cat","2018-2019"),
new Project("Pete the Cat: A Very Groovy Christmas","2018"),
new Project("BoJack Horseman","2016-2018"),
new Project("Justin Timberlake: Man of the Woods","2018"),
new Project("Shock and Awe","2017"),
new Project("The Sinner","2017"),
new Project("Spark: A Space Tail","2016"),
new Project("A Kind of Murder","2016"),
new Project("The Book of Love","2016"),
new Project("Bleeding Heart","2015"),
new Project("Accidental Love","2015"),
new Project("New Girl","2014"),
new Project("Family Guy","2005-2013"),
new Project("The Truth About Emanuel","2013"),
new Project("Playing for Keeps","2012"),
new Project("Hitchcock","2012"),
new Project("Total Recall","2012/I"),
new Project("The Tall Man","2012"),
new Project("New Year's Eve","2011"),
new Project("The A-Team","2010"),
new Project("Valentine's Day","2010/I"),
new Project("Planet 51","2009"),
new Project("Guys and Dolls at the Hollywood Bowl","2009"),
new Project("Powder Blue","2009"),
new Project("Saturday Night Live","2009"),
new Project("Easy Virtue","2008"),
new Project("Hole in the Paper Sky","2008"),
new Project("I Now Pronounce You Chuck & Larry","2007"),
new Project("Next","2007"),
new Project("Vanity Fair: Killers Kill, Dead Men Die","2007"),
new Project("Home of the Brave","2006"),
new Project("7th Heaven","1996-2006"),
new Project("The Illusionist","2006"),
new Project("Elizabethtown","2005"),
new Project("London","2005/I"),
new Project("Stealth","2005"),
new Project("Blade: Trinity","2004"),
new Project("Cellular","2004"),
new Project("Johnny Bravo","2004"),
new Project("The Texas Chainsaw Massacre","2003"),
new Project("The Rules of Attraction","2002"),
new Project("Summer Catch","2001"),
new Project("Aerosmith: Fly Away from Here","2001"),
new Project("I'll Be Home for Christmas","1998"),
new Project("Ulee's Gold","1997"),
new Project("It's a Digital World","1994"),
new Project("The Sinner","2017-2020"),
new Project("Limetown","2019"),
new Project("The Book of Love","2016"),
new Project("The Short Game","2013"),
new Project("The Tall Man","2012"),
new Project("Hole in the Paper Sky","2008"),
new Project("Pete the Cat","2018"),
new Project("Valentine's Day","2010/I"),
new Project("Easy Virtue","2008"),
new Project("7th Heaven","1997-1999"),
new Project("I'll Be Home for Christmas","1998"),
new Project("Sodales","2010"),
new Project("Happy Valley","2008"),
new Project("Harnessing Speed: The Making of 'Stealth'","2005"),
new Project("The Late Late Show with James Corden","2017-2019"),
new Project("Entertainment Tonight","2007-2019"),
new Project("Late Night with Seth Meyers","2018-2019"),
new Project("The Tonight Show Starring Jimmy Fallon","2017-2019"),
new Project("The Ellen DeGeneres Show","2004-2019"),
new Project("CTV News at Six Toronto","2019"),
new Project("The 2019 ESPY Awards","2019"),
new Project("E! Live from the Red Carpet","2007-2018"),
new Project("The 70th Primetime Emmy Awards","2018"),
new Project("Today","2016-2018"),
new Project("The Late Show with Stephen Colbert","2017-2018"),
new Project("Celebrity Page","2017-2018"),
new Project("Wimbledon","2018"),
new Project("Extra with Billy Bush","2016-2018"),
new Project("Variety Studio: Actors on Actors","2018"),
new Project("Good Morning America","2012-2018"),
new Project("Access Hollywood","2017-2018"),
new Project("God kveld Norge","2018"),
new Project("The 23rd Annual Critics' Choice Awards","2018"),
new Project("2018 Golden Globes Arrivals Special","2018"),
new Project("75th Golden Globe Awards","2018"),
new Project("The 69th Primetime Emmy Awards","2017"),
new Project("Chelsea","2017"),
new Project("Live! with Kelly","2004-2017"),
new Project("The Insider","2017"),
new Project("Who Do You Think You Are?","2017"),
new Project("Good Morning Britain","2017"),
new Project("Lorraine","2017"),
new Project("The Oscars","2017"),
new Project("Jimmy Kimmel Live!","2003-2017"),
new Project("Crazy About Tiffany's","2016"),
new Project("The Oscars","2014"),
new Project("JT: Reflections","2013"),
new Project("Celebrity Style Story","2013"),
new Project("Jason Bateman, Jessica Biel, and Josh Gad Support the Strike!","2013"),
new Project("The Tall Man: In the Shadow of the Tall Man","2013"),
new Project("Practically Real: The Action of 'Total Recall'","2012"),
new Project("Made in Hollywood","2010-2012"),
new Project("Up Close with Carrie Keagan","2007-2012"),
new Project("Big Morning Buzz Live","2012"),
new Project("Conan","2012"),
new Project("Late Show with David Letterman","2004-2012"),
new Project("Stand Up to Cancer","2012"),
new Project("Janela Indiscreta","2012"),
new Project("A Moment With","2012"),
new Project("The Big Picture","2012"),
new Project("The Daily Show","2012"),
new Project("Larry King Now","2012"),
new Project("The Tonight Show with Jay Leno","1999-2012"),
new Project("Comic Con 2012 Live","2012"),
new Project("2012 MTV Movie Awards","2012"),
new Project("Always Open","2012"),
new Project("The 69th Annual Golden Globe Awards","2012"),
new Project("Wetten, dass..?","2011"),
new Project("The Graham Norton Show","2008-2011"),
new Project("TeenNick Halo Awards","2011"),
new Project("The A-Team: Plan of Attack","2010"),
new Project("The A Team: T4 Premiere Special","2010"),
new Project("Mark at the Movies","2010"),
new Project("Le grand journal de Canal+","2010"),
new Project("The 7PM Project","2010"),
new Project("Late Night with Jimmy Fallon","2009-2010"),
new Project("2010 MTV Movie Awards","2010"),
new Project("MTV Movie Awards 2010 Pre-Show","2010"),
new Project("Guys Choice","2010"),
new Project("Life on Planet 51","2010"),
new Project("Summit on the Summit","2010"),
new Project("The Jay Leno Show","2010"),
new Project("The Tonight Show with Conan O'Brien","2009"),
new Project("Shooting Blue","2009"),
new Project("Saturday Night Live","2009"),
new Project("The 81st Annual Academy Awards","2009"),
new Project("The 2nd Annual CNN Heroes: An All-Star Tribute","2008"),
new Project("Xpose","2008"),
new Project("NRJ 12: Scream Awards","2007"),
new Project("Scream Awards 2007","2007"),
new Project("Making the Best Next Thing","2007"),
new Project("Next: Two Minutes in the Future with Jessica Biel","2007"),
new Project("Weekend Sunrise","2007"),
new Project("Getaway","2007"),
new Project("Your Mommy Kills Animals!","2007"),
new Project("Late Night with Conan O'Brien","2005-2007"),
new Project("HBO First Look","2007"),
new Project("2007 MTV Movie Awards","2007"),
new Project("HypaSpace","2006-2007"),
new Project("The View","2007"),
new Project("The 79th Annual Academy Awards","2007"),
new Project("Shootout","2007"),
new Project("The 12th Annual Critics' Choice Awards","2007"),
new Project("The 64th Annual Golden Globe Awards","2007"),
new Project("Jessica Biel on the Illusionist","2007"),
new Project("The Making of 'The Illusionist'","2007"),
new Project("Golden Karma Awards","2006"),
new Project("'London': Behind the Scenes","2006"),
new Project("Harnessing Speed: The Making of 'Stealth'","2005"),
new Project("Rove Live","2005"),
new Project("Corazon de...","2005"),
new Project("Total Request Live","2004-2005"),
new Project("ESPY Awards","2005"),
new Project("2005 MTV Movie Awards","2005"),
new Project("Nightstalkers, Daywalkers, and Familiars: Inside the World of 'Blade Trinity'","2005"),
new Project("Chainsaw Redux: Making a Massacre","2004"),
new Project("2004 MTV Movie Awards","2004"),
new Project("MTV Movie Awards 2004 Pre-Show","2004"),
new Project("Pepsi Smash","2003"),
new Project("Punk'd","2003"),
new Project("Trading Spaces","2003"),
new Project("Rank","2001-2002"),
new Project("The 2002 Billboard Music Awards","2002"),
new Project("The Late Late Show with Craig Kilborn","2002"),
new Project("Total Access 24/7","2001"),
new Project("Celebrity Adventures","2001"),
new Project("The Teen Choice Awards 2001","2001"),
new Project("Nickelodeon Kids' Choice Awards '99","1999"),
new Project("MuchOnDemand","1997"),
new Project("Entertainment Tonight","2015-2020"),
new Project("Celebrity Page","2017-2020"),
new Project("Extra with Billy Bush","2015-2019"),
new Project("The Insider","2014-2017"),
new Project("Abandoned","2017"),
new Project("Access Hollywood","2017"),
new Project("Inside Edition","2014-2015"),
new Project("The Graham Norton Show","2008-2011"),
new Project("Almost Famous IV","2011"),
new Project("Live from Studio Five","2010"),
new Project("Biography","2009"),
new Project("Trading Spaces","2007"),
new Project("Guys Choice","2007"),
new Project("Going to Pieces: The Rise and Fall of the Slasher Film","2006"),
new Project("7th Heaven","2003-2006"),
new Project("100 Greatest Teen Stars","2006"),
new Project("101 Sexiest Celebrity Bodies","2005"),
new Project("Frontline","2001")]),
			new Contact("C004","scarjo", "scarlett johansson", "22-nov-1984", "female", "18 dahlia avenue", "sjo@ironman2.org", "images/004.jpg", [new Project("Little Shop of Horrors",null),
new Project("Sing 2","2021"),
new Project("Black Widow","2020"),
new Project("Jojo Rabbit","2019"),
new Project("Marriage Story","2019"),
new Project("Avengers: Endgame","2019"),
new Project("Captain Marvel","2019"),
new Project("Saturday Night Live","2009-2018"),
new Project("Avengers: Infinity War","2018"),
new Project("Pete Yorn, Scarlett Johansson: Bad Dreams","2018"),
new Project("Isle of Dogs","2018"),
new Project("Rough Night","2017"),
new Project("Ghost in the Shell","2017"),
new Project("Sing","2016"),
new Project("Captain America: Civil War","2016"),
new Project("The Jungle Book","2016"),
new Project("Hail, Caesar!","2016"),
new Project("Avengers: Age of Ultron","2015"),
new Project("Assassin Banana","2015"),
new Project("Lucy","2014/I"),
new Project("Deep Down","2014"),
new Project("Captain America: The Winter Soldier","2014"),
new Project("Chef","2014"),
new Project("HitRECord on TV","2014"),
new Project("Her","2013"),
new Project("Under the Skin","2013/I"),
new Project("Don Jon","2013"),
new Project("Hitchcock","2012"),
new Project("The Avengers","2012"),
new Project("We Bought a Zoo","2011"),
new Project("Iron Man 2","2010"),
new Project("He's Just Not That Into You","2009"),
new Project("The Spirit","2008"),
new Project("Vicky Cristina Barcelona","2008"),
new Project("Robot Chicken","2005-2008"),
new Project("The Other Boleyn Girl","2008"),
new Project("Will.i.am: Yes We Can","2008"),
new Project("The Nanny Diaries","2007"),
new Project("Justin Timberlake: What Goes Around ...Comes Around","2007"),
new Project("Bob Dylan: When the Deal Goes Down","2006"),
new Project("The Prestige","2006"),
new Project("The Black Dahlia","2006"),
new Project("Scoop","2006"),
new Project("The Island","2005"),
new Project("Match Point","2005"),
new Project("A Love Song for Bobby Long: Deleted Scenes","2004"),
new Project("In Good Company","2004"),
new Project("The SpongeBob Squarepants Movie","2004"),
new Project("The SpongeBob SquarePants Movie","2004"),
new Project("A Good Woman","2004"),
new Project("A Love Song for Bobby Long","2004"),
new Project("The Perfect Score","2004"),
new Project("Girl with a Pearl Earring","2003"),
new Project("Lost in Translation","2003"),
new Project("Eight Legged Freaks","2002"),
new Project("An American Rhapsody","2001"),
new Project("Ghost World","2001"),
new Project("The Man Who Wasn't There","2001"),
new Project("My Brother the Pig","1999"),
new Project("The Horse Whisperer","1998"),
new Project("Home Alone 3","1997"),
new Project("Fall","1997"),
new Project("If Lucy Fell","1996"),
new Project("Manny & Lo","1996"),
new Project("The Client","1995"),
new Project("Just Cause","1995"),
new Project("North","1994"),
new Project("Marriage Story","2019"),
new Project("Bons baisers d'Europe","2019"),
new Project("The Tonight Show Starring Jimmy Fallon","2016-2018"),
new Project("Good Morning Britain","2016"),
new Project("Sing","2016"),
new Project("The Jungle Book","2016"),
new Project("Her","2013"),
new Project("The Oscars","2013"),
new Project("Mulatschag","2012"),
new Project("Chasing Ice","2012"),
new Project("Days of Grace","2011"),
new Project("Wretches & Jabberers","2011"),
new Project("Late Night with Jimmy Fallon","2010"),
new Project("20 to 1","2010"),
new Project("Gossip Girl","2010"),
new Project("Scarlett Johansson: Falling Down","2008"),
new Project("The Nanny Diaries","2007"),
new Project("Saturday Night Live","2006-2007"),
new Project("Lost in Translation","2003"),
new Project("Black Widow","2020"),
new Project("The Whale","2011"),
new Project("American Express Unstaged: Ellie Goulding","2015"),
new Project("These Vagabond Shoes","2009"),
new Project("Scarlett Johansson: Falling Down","2008"),
new Project("How to Live Forever","2017"),
new Project("Marvel Studios: Assembling a Universe","2014"),
new Project("HBO First Look","2011"),
new Project("Buck","2011"),
new Project("Fantaisie in Bubblewrap","2007"),
new Project("Broadway: The Next Generation",null),
new Project("Entertainment Tonight","2007-2020"),
new Project("Jimmy Kimmel Live!","2011-2020"),
new Project("The Oscars","2020"),
new Project("35th Film Independent Spirit Awards","2020"),
new Project("CBS News Sunday Morning","2013-2020"),
new Project("EE British Academy Film Awards","2020"),
new Project("The 26th Annual Screen Actors Guild Awards","2020"),
new Project("Close Up with the Hollywood Reporter","2020"),
new Project("2020 Golden Globe Awards","2020"),
new Project("IMDb at the Golden Globes","2020"),
new Project("Saturday Night Live","2006-2019"),
new Project("Hollywood Insider","2019"),
new Project("The Late Show with Stephen Colbert","2015-2019"),
new Project("Live! with Kelly","1998-2019"),
new Project("The Tonight Show Starring Jimmy Fallon","2015-2019"),
new Project("The Ellen DeGeneres Show","2005-2019"),
new Project("Entertainment Tonight Canada","2019"),
new Project("CTV News at Noon Toronto","2019"),
new Project("CTV News at 11:30 Toronto","2019"),
new Project("Celebrity Page","2017-2019"),
new Project("Good Morning America","2012-2019"),
new Project("Complex x Fuse","2019"),
new Project("This Morning","2019"),
new Project("Dagsrevyen","2019"),
new Project("Red Carpet Report","2019"),
new Project("Marvel Studios' Avengers: Endgame LIVE Red Carpet World Premiere","2019"),
new Project("Lorraine","2019"),
new Project("The Chris Moyles Show on Radio X","2019"),
new Project("Good Morning Britain","2017-2019"),
new Project("Hot Ones","2019"),
new Project("Access Hollywood","2017-2019"),
new Project("This Is What Democracy Looks Like","2018"),
new Project("Conan","2018"),
new Project("Dish Nation","2018"),
new Project("Extra with Billy Bush","2014-2018"),
new Project("Finding Your Roots with Henry Louis Gates, Jr.","2017"),
new Project("Ghost in the Shell: Hard-Wired Humanity - Making Ghost in the Shell","2017"),
new Project("Man & Machine: The Ghost Philosophy","2017"),
new Project("Section 9: Cyber Defenders","2017"),
new Project("Inside the Actors Studio","2017"),
new Project("The Chew","2017"),
new Project("The Insider","2014-2017"),
new Project("The 71st Annual Tony Awards","2017"),
new Project("Art as Dialogue","2017"),
new Project("God kveld Norge","2017"),
new Project("Late Night with Seth Meyers","2017"),
new Project("La noche de los Oscar","2017"),
new Project("E! Live from the Red Carpet","2006-2017"),
new Project("The Oscars","2017"),
new Project("United We Stand, Divided We Fall: The Making of 'Captain America: Civil War'","2016"),
new Project("An Era of Glamour","2016"),
new Project("Directing Hollywood","2016"),
new Project("Floyd Norman: An Animated Life","2016"),
new Project("All-Star Dog Rescue Celebration","2015"),
new Project("Avengers: Age of Ultron - From the Inside Out: Making of Avengers - Age of Ultron","2015"),
new Project("Avengers: Age of Ultron - Global Adventure","2015"),
new Project("MTV After Hours with Josh Horowitz","2015"),
new Project("Made in Hollywood","2010-2015"),
new Project("Late Show with David Letterman","1998-2015"),
new Project("2015 MTV Movie Awards","2015"),
new Project("MTV Movie Awards Red Carpet","2015"),
new Project("The Oscars","2015"),
new Project("Lucy: The Evolution of Lucy","2015"),
new Project("The Barbara Walters Summer Special","2014"),
new Project("24th Annual Gotham Independent Film Awards","2014"),
new Project("On the Frontline: An Inside Look at Captain America's Battlegrounds","2014"),
new Project("E! News","2014"),
new Project("2014 MTV Movie Awards","2014"),
new Project("MTV Movie Awards Takeover","2014"),
new Project("The Queen Latifah Show","2014"),
new Project("The Late Late Show with Craig Ferguson","2010-2014"),
new Project("Ant & Dec's Saturday Night Takeaway","2014"),
new Project("Taff","2014"),
new Project("Marvel Studios: Assembling a Universe","2014"),
new Project("Rencontres de cinema","2014"),
new Project("La nuit des Cesars","2014"),
new Project("19th Annual Critics' Choice Movie Awards","2014"),
new Project("The Daily Show","2014"),
new Project("Good Day L.A.","2013"),
new Project("Late Night with Jimmy Fallon","2010-2013"),
new Project("The 67th Annual Tony Awards","2013"),
new Project("ES.TV HD","2013"),
new Project("Close Up","2012"),
new Project("Evening Urgant","2012"),
new Project("The Avengers: Assembling the Ultimate Team","2012"),
new Project("The Avengers: A Visual Journey","2012"),
new Project("The Tonight Show with Jay Leno","2004-2012"),
new Project("Buenas noches y Buenafuente","2012"),
new Project("Daybreak","2012"),
new Project("Fantastic","2012"),
new Project("VIP zpravy","2012"),
new Project("Escape from the World's Most Dangerous Place","2012"),
new Project("The Avengers Assemble Premiere","2012"),
new Project("YourGeekNews.com","2012"),
new Project("Biography","2011"),
new Project("In Character With...","2011"),
new Project("American Masters","2011"),
new Project("Road to 'The Avengers'","2011"),
new Project("Guys Choice Awards 2011","2011"),
new Project("The 83rd Annual Academy Awards","2011"),
new Project("The 68th Annual Golden Globe Awards","2011"),
new Project("Iron Man 2: Illustrated Origin","2010"),
new Project("Ultimate Iron Man","2010"),
new Project("The 64th Annual Tony Awards","2010"),
new Project("2010 MTV Movie Awards","2010"),
new Project("The 76th Annual Drama League Awards","2010"),
new Project("Mark at the Movies","2010"),
new Project("Guys Choice","2010"),
new Project("The Red Carpet Issue","2010"),
new Project("Fearne and...","2009"),
new Project("Le grand journal de Canal+","2008-2009"),
new Project("The Spirit: Green World","2009"),
new Project("The Spirit: History Repeats","2009"),
new Project("Up Close with Carrie Keagan","2009"),
new Project("Artist on Artist","2008"),
new Project("Cinema 3","2008"),
new Project("Nobel Peace Prize Concert","2008"),
new Project("Cartelera","2008"),
new Project("Dias de cine","2008"),
new Project("2008 MTV Video Music Awards","2008"),
new Project("Stand Up to Cancer","2008"),
new Project("The Teen Choice Awards 2008","2008"),
new Project("On Set: Making Boleyn","2008"),
new Project("To Be a Lady","2008"),
new Project("Translating History to Screen","2008"),
new Project("Tomtesterom","2008"),
new Project("Scarlett Johansson: Falling Down","2008"),
new Project("Today","2005-2008"),
new Project("Late Night with Conan O'Brien","2003-2007"),
new Project("The Director's Notebook: The Cinematic Sleight of Hand of Christopher Nolan","2007"),
new Project("The Prestige: Now That's Magic","2006"),
new Project("Made in Hollywood: Teen Edition","2006"),
new Project("Showbiz Tonight","2006"),
new Project("Movie Rush","2006"),
new Project("Forbes Celebrity 100: Who Made Bank?","2006"),
new Project("The 63rd Annual Golden Globe Awards","2006"),
new Project("Silenci?","2005"),
new Project("HBO First Look","2005"),
new Project("The 77th Annual Academy Awards","2005"),
new Project("The 62nd Annual Golden Globe Awards","2005"),
new Project("Entourage","2004"),
new Project("2004 MTV Movie Awards","2004"),
new Project("MTV Movie Awards 2004 Pre-Show","2004"),
new Project("The 58th Annual Tony Awards","2004"),
new Project("The 76th Annual Academy Awards","2004"),
new Project("Brit Awards 2004","2004"),
new Project("The Orange British Academy Film Awards","2004"),
new Project("Lost on Location: Behind the Scenes of 'Lost in Translation'","2004"),
new Project("Anatomy of a Scene","2004"),
new Project("The 61st Annual Golden Globe Awards","2004"),
new Project("The Sharon Osbourne Show","2004"),
new Project("Tinseltown TV","2004"),
new Project("The 2003 IFP Independent Spirit Awards","2003"),
new Project("Making of 'Ghost World'","2002"),
new Project("The Late Late Show with Craig Kilborn","2002"),
new Project("Brit Awards 2002","2002"),
new Project("Sondagsoppet","1998"),
new Project("The Rosie O'Donnell Show","1998"),
new Project("Jet 7","1996"),
new Project("420 AWARDS - 2nd Annual Event","2020"),
new Project("Celebrity Page","2017-2020"),
new Project("Entertainment Tonight","2014-2020"),
new Project("Celebrating Marvel's Stan Lee","2019/II"),
new Project("Extra with Billy Bush","2015-2019"),
new Project("Robert Redford: The Golden Look","2019"),
new Project("The Movies","2019"),
new Project("The Ellen DeGeneres Show","2007-2019"),
new Project("Entertainment Tonight Canada","2019"),
new Project("The Chris Moyles Show on Radio X","2019"),
new Project("Taff","2010-2018"),
new Project("Hell's Club Part 2. Another Night","2017"),
new Project("La petite histoire des super-heros","2017"),
new Project("The Insider","2017"),
new Project("Sing: The Sing Network","2017"),
new Project("Good Morning Britain","2017"),
new Project("Corta por Lozano","2017"),
new Project("Lorraine","2017"),
new Project("Nunca es tarde","2017"),
new Project("The FalconCast Awards","2016"),
new Project("Inside Edition","2014-2016"),
new Project("L'IA et Mathieu","2016"),
new Project("Lego Marvel's Avengers","2016"),
new Project("Il etait une fois...","2015"),
new Project("Un soir a la Tour Eiffel","2015"),
new Project("Les Chroniques du Mea","2014"),
new Project("Movie Guide","2013"),
new Project("RuPaul's Drag Race","2013"),
new Project("Mulatschag","2012"),
new Project("Welcome to the Basement","2012"),
new Project("Made in Hollywood","2012"),
new Project("Final Cut: Ladies and Gentlemen","2012"),
new Project("Bert Stern: Original Madman","2011"),
new Project("Buck","2011"),
new Project("20 to 1","2009-2010"),
new Project("Richard Roeper & the Movies","2010"),
new Project("Presidentti Ahtisaaren Nobel-vuosi","2009"),
new Project("Saturday Night Live: The Best of Amy Poehler","2009"),
new Project("Buscando a Penelope","2009"),
new Project("Los 10 magnificos","2008"),
new Project("Ceremonia de inauguracion - 56 Festival internacional de cine de San Sebastian","2008"),
new Project("The O'Reilly Factor","2008"),
new Project("Forbes 20 Under 25: Young, Rich and Famous","2007"),
new Project("XXI Premios Anuales de la Academia","2007"),
new Project("Kig Ind TV","2007"),
new Project("Headline News","2006"),
new Project("50 premios Sant Jordi de cinematografia","2006"),
new Project("XX premios Goya","2006"),
new Project("Corazon de...","2005"),
new Project("Silenci?","2005"),
new Project("101 Sexiest Celebrity Bodies","2005"),
new Project("Continuara...","2005"),
new Project("El Magacine","2005"),
new Project("Buenafuente","2005"),
new Project("Cinema mil","2005")]),
			new Contact("C005","brad", "william bradley pitt", "18-dec-1963", "male", "#43 hollywood blvd", "jsmith@meetjoeblack.gov", "images/005.jpg", [new Project("Untitled Chris Cornell Documentary","2021"),
new Project("Wrong Answer",null),
new Project("Black Hole",null),
new Project("The Curious Incident of the Dog in the Night-Time",null),
new Project("Americanah","2020"),
new Project("The Underground Railroad",null),
new Project("Blonde","2020"),
new Project("Irresistible","2020"),
new Project("Lego Masters","2020"),
new Project("Kajillionaire","2020"),
new Project("The King","2019/I"),
new Project("Ad Astra","2019"),
new Project("Sweetbitter",null),
new Project("The OA","2016-2019"),
new Project("The Last Black Man in San Francisco","2019"),
new Project("Vice","2018/I"),
new Project("If Beale Street Could Talk","2018"),
new Project("Beautiful Boy","2018/I"),
new Project("Brad's Status","2017"),
new Project("War Machine","2017"),
new Project("Okja","2017"),
new Project("The Lost City of Z","2016"),
new Project("Voyage of Time: The IMAX Experience","2016"),
new Project("Voyage of Time: Life's Journey","2016"),
new Project("Moonlight","2016/I"),
new Project("The Big Short","2015"),
new Project("By the Sea","2015"),
new Project("Hitting the Apex","2015"),
new Project("True Story","2015/I"),
new Project("Selma","2014/I"),
new Project("Fury","2014"),
new Project("P.O.V.","2014"),
new Project("Nightingale","2014/II"),
new Project("The Normal Heart","2014"),
new Project("Resurrection","2014"),
new Project("12 Years a Slave","2013"),
new Project("Kick-Ass 2","2013"),
new Project("World War Z","2013"),
new Project("Big Men","2013"),
new Project("Independent Lens","2013"),
new Project("Killing Them Softly","2012"),
new Project("The House I Live In","2012"),
new Project("Moneyball","2011"),
new Project("The Tree of Life","2011"),
new Project("Eat Pray Love","2010"),
new Project("Kick-Ass","2010"),
new Project("The Time Traveler's Wife","2009"),
new Project("The Private Lives of Pippa Lee","2009"),
new Project("Pretty/Handsome","2008"),
new Project("The Assassination of Jesse James by the Coward Robert Ford","2007"),
new Project("A Mighty Heart","2007"),
new Project("The Tehuacan Project","2007"),
new Project("Year of the Dog","2007/I"),
new Project("Running with Scissors","2006"),
new Project("The Departed","2006"),
new Project("God Grew Tired of Us","2006"),
new Project("Babylon","2021"),
new Project("Ad Astra","2019"),
new Project("Once Upon a Time... in Hollywood","2019"),
new Project("The Jim Jefferies Show","2017-2018"),
new Project("Deadpool 2","2018"),
new Project("War Machine","2017"),
new Project("Allied","2016"),
new Project("Voyage of Time: The IMAX Experience","2016"),
new Project("The Big Short","2015"),
new Project("By the Sea","2015"),
new Project("The Audition","2015/III"),
new Project("Fury","2014"),
new Project("The Counselor","2013"),
new Project("12 Years a Slave","2013"),
new Project("World War Z","2013"),
new Project("Killing Them Softly","2012"),
new Project("8","2012"),
new Project("Touch of Evil","2011"),
new Project("Happy Feet Two","2011"),
new Project("Moneyball","2011"),
new Project("The Tree of Life","2011"),
new Project("Megamind","2010"),
new Project("Beyond All Boundaries","2009"),
new Project("Inglourious Basterds","2009"),
new Project("The Curious Case of Benjamin Button","2008"),
new Project("Burn After Reading","2008"),
new Project("The Assassination of Jesse James by the Coward Robert Ford","2007"),
new Project("Ocean's Thirteen","2007"),
new Project("Babel","2006/I"),
new Project("Mr. & Mrs. Smith","2005"),
new Project("Ocean's Twelve","2004"),
new Project("Troy","2004"),
new Project("Freedom: A History of Us","2003"),
new Project("Sinbad and the Cyclops Island","2003"),
new Project("King of the Hill","2003"),
new Project("Sinbad: Legend of the Seven Seas","2003"),
new Project("Confessions of a Dangerous Mind","2002"),
new Project("Ocean's Eleven","2001"),
new Project("Friends","2001"),
new Project("Spy Game","2001"),
new Project("The Mexican","2001"),
new Project("Snatch","2000"),
new Project("Fight Club","1999"),
new Project("Being John Malkovich","1999"),
new Project("Meet Joe Black","1998"),
new Project("Seven Years in Tibet","1997"),
new Project("The Devil's Own","1997"),
new Project("Sleepers","1996"),
new Project("12 Monkeys","1995"),
new Project("Se7en","1995"),
new Project("Legends of the Fall","1994"),
new Project("Interview with the Vampire: The Vampire Chronicles","1994"),
new Project("The Favor","1994"),
new Project("True Romance","1993"),
new Project("Kalifornia","1993"),
new Project("Contact","1992"),
new Project("A River Runs Through It","1992"),
new Project("Tales from the Crypt","1992"),
new Project("Cool World","1992"),
new Project("Two-Fisted Tales","1992"),
new Project("Johnny Suede","1991"),
new Project("Thelma & Louise","1991"),
new Project("Glory Days","1990"),
new Project("Across the Tracks","1990"),
new Project("Too Young to Die?","1990"),
new Project("The Image","1990"),
new Project("Thirtysomething","1989"),
new Project("Happy Together","1989"),
new Project("Cutting Class","1989"),
new Project("Growing Pains","1987-1989"),
new Project("Freddy's Nightmares","1989"),
new Project("Head of the Class","1989"),
new Project("The Dark Side of the Sun","1988"),
new Project("A Stoning in Fulham County","1988"),
new Project("21 Jump Street","1988"),
new Project("Dallas","1987-1988"),
new Project("Less Than Zero","1987"),
new Project("No Man's Land","1987"),
new Project("Another World","1987"),
new Project("Hunk","1987"),
new Project("Happy Feet Two","2011"),
new Project("Megamind","2010"),
new Project("The Game Changer","2019"),
new Project("X-Men Mondays","2019"),
new Project("The Green Inferno","2013"),
new Project("Casting Couch","2013/I"),
new Project("Billy Beane: Re-Inventing the Game","2012"),
new Project("Exploring 'The Tree of Life'","2011"),
new Project("Before Breakfast","2010/I"),
new Project("Jane's Journey","2010"),
new Project("Where the Wild Things Are","2009"),
new Project("Stuntmen","2009"),
new Project("Visual Acoustics","2008"),
new Project("Haggard","2003"),
new Project("Jackass","2001-2002"),
new Project("Being John Malkovich","1999"),
new Project("Answers to Questions You Didn't Know to Ask About Climate Change","2020"),
new Project("Entertainment Tonight","2003-2020"),
new Project("Good Morning America","2007-2020"),
new Project("Jimmy Kimmel Live!","2007-2020"),
new Project("Live! with Kelly","2007-2020"),
new Project("Red! - Stars, Lifestyle & More","2020"),
new Project("The Oscars","2020"),
new Project("Celebrity Page","2020"),
new Project("Access Hollywood","2008-2020"),
new Project("Extra with Billy Bush","2003-2020"),
new Project("The 26th Annual Screen Actors Guild Awards","2020"),
new Project("Made in Hollywood","2020"),
new Project("2020 Golden Globe Awards","2020"),
new Project("Dish Nation","2019"),
new Project("Hollywood Insider","2019"),
new Project("The Tonight Show Starring Jimmy Fallon","2014-2019"),
new Project("The Ellen DeGeneres Show","2008-2019"),
new Project("Dias de cine","2009-2019"),
new Project("Entertainers with Byron Allen","2019"),
new Project("Jacksepticeye","2019"),
new Project("Good Morning Britain","2019"),
new Project("WGN Morning News","2019"),
new Project("Today","1995-2019"),
new Project("Entertainment Tonight Canada","2019"),
new Project("Glastonbury 2017","2017"),
new Project("The Late Show with Stephen Colbert","2017"),
new Project("74th Golden Globe Awards","2017"),
new Project("The Oscars","2016"),
new Project("73rd Golden Globe Awards","2016"),
new Project("The Insider","2008-2015"),
new Project("Hitting the Apex","2015"),
new Project("Fury: Blood Brothers","2015"),
new Project("Fury: Director's Combat Journal","2015"),
new Project("No Guts, No Glory: The Horrors of Combat","2015"),
new Project("Taming the Beasts: How to Drive, Fire and Shoot Inside a 30-Ton Tank","2015"),
new Project("Inside Edition","2014"),
new Project("Between Two Ferns with Zach Galifianakis","2014"),
new Project("Le grand journal de Canal+","2014"),
new Project("Vivement dimanche prochain","2014"),
new Project("E! News","2014"),
new Project("Pros and Cons: Inside Ocean's Outfit","2014"),
new Project("Tosh.0","2014"),
new Project("The Oscars","2014"),
new Project("The 2014 Film Independent Spirit Awards","2014"),
new Project("The EE British Academy Film Awards","2014"),
new Project("19th Annual Critics' Choice Movie Awards","2014"),
new Project("Profiles in Philanthropy","2012-2013"),
new Project("HBO First Look","2001-2013"),
new Project("A Look at the Creation of World War Z's Zombies","2013"),
new Project("Evening Urgant","2013"),
new Project("35-y Moskovskiy mezhdunarodnyy kinofestival","2013"),
new Project("Late Night with Jimmy Fallon","2013"),
new Project("Taff","2001-2013"),
new Project("2013 MTV Movie Awards","2013"),
new Project("The Making of 'Killing Them Softly'","2013"),
new Project("Celebrity Style Story","2012"),
new Project("Chanel No. 5: There You Are","2012"),
new Project("Chanel No. 5: Wherever I Go","2012"),
new Project("La classe americaine","2012"),
new Project("Close Up","2012"),
new Project("Panico na TV","2012"),
new Project("The 84th Annual Academy Awards","2012"),
new Project("The Orange British Academy Film Awards","2012"),
new Project("The Orange British Academy Film Awards: Red Carpet","2012"),
new Project("Inside the Actors Studio","2012"),
new Project("CBS This Morning","2012"),
new Project("The Daily Show","2012"),
new Project("18th Annual Screen Actors Guild Awards","2012"),
new Project("CBS News Sunday Morning","2012"),
new Project("CBS This Morning: Saturday","2012"),
new Project("Janela Indiscreta","2012"),
new Project("The 69th Annual Golden Globe Awards","2012"),
new Project("17th Annual Critics' Choice Movie Awards","2012"),
new Project("Moneyball: Drafting the Team","2012"),
new Project("Moneyball: Playing the Game","2012"),
new Project("Charlie Rose","2008-2011"),
new Project("Studio 42 with Bob Costas","2011"),
new Project("At the Movies","2011"),
new Project("Cinema 3","1996-2011"),
new Project("Shownieuws","2011"),
new Project("Cannes Film Festival","2009-2011"),
new Project("Close Up","2011"),
new Project("His Way","2011"),
new Project("The 68th Annual Golden Globe Awards","2011"),
new Project("Live from Studio Five","2010"),
new Project("America's Game: The Superbowl Champions","2010"),
new Project("The Big Uneasy","2010"),
new Project("If God Is Willing and da Creek Don't Rise","2010"),
new Project("30 minuts","2010"),
new Project("Exit Through the Gift Shop","2010"),
new Project("Hope for Haiti Now: A Global Benefit for Earthquake Relief","2010"),
new Project("De schuld van VTM","2009"),
new Project("The Jeffrey Henderson Show","2009"),
new Project("SmapxSmap","2009"),
new Project("TMZ on TV","2009"),
new Project("Real Time with Bill Maher","2009"),
new Project("Punkt 12","2009"),
new Project("Spike's Guys Choice","2009"),
new Project("The Curious Birth of Benjamin Button","2009"),
new Project("The 81st Annual Academy Awards","2009"),
new Project("Eigo de shabera-night","2009"),
new Project("This Morning","2009"),
new Project("The Orange British Academy Film Awards","2009"),
new Project("The Orange British Academy Film Awards: Red Carpet","2009"),
new Project("15th Annual Screen Actors Guild Awards","2009"),
new Project("e2: The Economies of Being Environmentally Conscious","2006-2009"),
new Project("The 66th Annual Golden Globe Awards","2009"),
new Project("The 35th Annual People's Choice Awards","2009"),
new Project("Larry King Live","2007-2009"),
new Project("The Oprah Winfrey Show","1998-2008"),
new Project("Kinotipp","2008"),
new Project("His Highness Hollywood","2008"),
new Project("Tellement People","2008"),
new Project("American Idol","2008"),
new Project("The Assassination of Jesse James: Death of an Outlaw","2008"),
new Project("E! Live from the Red Carpet","2007-2008"),
new Project("Caiga quien caiga","2008"),
new Project("13th Annual Critics' Choice Awards","2008"),
new Project("13th Annual Critics' Choice Awards Red Carpet Premiere","2008"),
new Project("Julia Roberts: An American Cinematheque Tribute","2007"),
new Project("Don't Tell My Booker!!!","2007"),
new Project("Attacking Troy","2007"),
new Project("Troy in Focus","2007"),
new Project("Exterieur jour","2007"),
new Project("Buzz: AT&T Original Documentaries","2007"),
new Project("Biography","2004-2007"),
new Project("20 heures le journal","2007"),
new Project("The 64th Annual Golden Globe Awards","2007"),
new Project("Corazon de...","2005-2007"),
new Project("The Barbara Walters Summer Special","2006"),
new Project("San Sebastian 2006: Cronica de Carlos Boyero","2006"),
new Project("Film 2017","2006"),
new Project("Forbes Celebrity 100: Who Made Bank?","2006"),
new Project("Domestic Violence: Shooting Mr. & Mrs. Smith","2006"),
new Project("Brad Pitt Video Portrait","2006"),
new Project("Brisant","2006"),
new Project("The 32nd Annual People's Choice Awards","2006"),
new Project("Primetime Live: Brad Pitt's Journey to Africa","2005"),
new Project("Rx for Survival: A Global Health Challenge","2005"),
new Project("Live 8","2005"),
new Project("GMTV","2005"),
new Project("Special Thanks to Roy London","2005"),
new Project("Los Angeles","2005"),
new Project("Unscripted","2005"),
new Project("Tsunami Aid: A Concert of Hope","2005"),
new Project("Troy: From Ruins to Reality","2005"),
new Project("Troy: In the Thick of Battle","2005"),
new Project("Beer Run","2005"),
new Project("Tout le monde en parle","2004"),
new Project("Blue Collar TV","2004"),
new Project("The 56th Annual Primetime Emmy Awards","2004"),
new Project("Troy: The Passion of Helen","2004"),
new Project("The Making of 'Troy'","2004"),
new Project("4Pop","2004"),
new Project("Late Night with Conan O'Brien","2004"),
new Project("Total Request Live","2004"),
new Project("Hollywood Greats","2004"),
new Project("The Directors","1999-2003"),
new Project("The Fabulous Life of","2003"),
new Project("The Making of 'Sinbad: Legend of the Seven Seas'","2003"),
new Project("Abby Singer","2003"),
new Project("Nickelodeon Kids' Choice Awards '03","2003"),
new Project("The 2003 IFP Independent Spirit Awards","2003"),
new Project("Cartaz Cultural","2003"),
new Project("The 60th Annual Golden Globe Awards","2003"),
new Project("Saturday Night Live","1998-2002"),
new Project("The 54th Annual Primetime Emmy Awards","2002"),
new Project("Full Frontal","2002"),
new Project("Jeff Buckley: Everybody Here Wants You","2002"),
new Project("Thelma & Louise: The Last Journey","2002"),
new Project("Rank","2002"),
new Project("'Ocean's Eleven': The Look of the Con","2002"),
new Project("Jackass","2001-2002"),
new Project("The 59th Annual Golden Globe Awards","2002"),
new Project("Bravo Profiles","2001"),
new Project("The Making of 'Spy Game'","2001"),
new Project("Travel Sick","2001"),
new Project("The Tonight Show with Jay Leno","2001"),
new Project("America: A Tribute to Heroes","2001"),
new Project("Growing Up Grizzly","2001"),
new Project("Making 'Snatch'","2001"),
new Project("AFI Life Achievement Award: A Tribute to Harrison Ford","2000"),
new Project("Lux","2000"),
new Project("On Location: Fight Club","2000"),
new Project("Flogging 'Fight Club'","2000"),
new Project("The 72nd Annual Academy Awards","2000"),
new Project("The 51st Annual Primetime Emmy Awards","1999"),
new Project("The Howard Stern Radio Show","1999"),
new Project("Intimate Portrait","1999"),
new Project("Bravo Profiles: The Entertainment Business","1998"),
new Project("Kalifornia: Interview with Juliette Lewis and Brad Pitt","1997"),
new Project("The Making of 'Kalifornia'","1997"),
new Project("Town Meeting with Diane Sawyer: Celebrities vs. the Press","1997"),
new Project("Corazon, corazon","1997"),
new Project("Mezamashi TV","1996"),
new Project("The Hamster Factor and Other Tales of Twelve Monkeys","1996"),
new Project("1996 MTV Movie Awards","1996"),
new Project("At the Movies","1996"),
new Project("The 68th Annual Academy Awards","1996"),
new Project("The 53rd Annual Golden Globe Awards","1996"),
new Project("1995 MTV Movie Awards","1995"),
new Project("The 67th Annual Academy Awards","1995"),
new Project("The 52nd Annual Golden Globe Awards","1995"),
new Project("VH1 Honors","1994"),
new Project("7th Annual Independent Spirit Awards","1992"),
new Project("The 64th Annual Academy Awards","1992"),
new Project("1990 MTV Video Music Awards","1990"),
new Project("The New Hollywood Squares","1988"),
new Project("Entertainment Tonight","2005-2020"),
new Project("Good Morning Britain","2016-2020"),
new Project("Celebrity Page","2017-2020"),
new Project("ITV Lunchtime News","2020"),
new Project("Extra with Billy Bush","2014-2020"),
new Project("Access Hollywood","2016-2019"),
new Project("Robert Redford: The Golden Look","2019"),
new Project("The IMDb Show","2019"),
new Project("Salvame Deluxe","2019"),
new Project("Les Chroniques du Mea","2018"),
new Project("The Zen Diaries of Garry Shandling","2018"),
new Project("Six Sides of Katharine Hepburn","2018"),
new Project("The Insider","2014-2017"),
new Project("Strange Inheritance","2017"),
new Project("TIME Presents: Celebrities on Trial","2017"),
new Project("Brangelina - Wie Hollywoods beruhmteste Liebe zerbrach","2017"),
new Project("Hoy nos toca","2017"),
new Project("Inside Edition","2014-2016"),
new Project("Welcome to the Basement","2014-2016"),
new Project("Boots on the Ground in Haiti","2016"),
new Project("Eamonn and Ruth: How the Other Half Lives","2015"),
new Project("Stretch Marks","2015"),
new Project("Charlie Brooker's 2014 Wipe","2014"),
new Project("Mobilize","2014"),
new Project("The Tonight Show with Jay Leno","2012-2014"),
new Project("Jennifer Aniston - Hollywoods einsame Traumfrau","2013"),
new Project("Troldspejlet","2009-2013"),
new Project("Taff","2004-2013"),
new Project("People Magnet TV","2013"),
new Project("CBS News Sunday Morning","2013"),
new Project("Chelsea Lately","2012"),
new Project("Chanel N5: Pour la premiere fois","2012"),
new Project("Final Cut: Ladies and Gentlemen","2012"),
new Project("1st AACTA Awards","2012"),
new Project("Mineseeker: The Mike Kendrick interview","2011"),
new Project("Late Night with Jimmy Fallon","2011"),
new Project("Basta","2011"),
new Project("Gilles Jacob: CIitizen Cannes","2010"),
new Project("Never Sleep Again: The Elm Street Legacy","2010"),
new Project("Bad Boy Kummer","2010"),
new Project("Live from Studio Five","2010"),
new Project("20 to 1","2006-2010"),
new Project("Smash His Camera","2010"),
new Project("The Tonight Show with Conan O'Brien","2009"),
new Project("WWE Raw","2009"),
new Project("Secrets of Body Language","2008"),
new Project("Premio Donostia a Antonio Banderas","2008"),
new Project("Corazon, corazon","2008"),
new Project("The O'Reilly Factor","2008"),
new Project("Hillary! Uncensored: Banned by the Media","2008"),
new Project("Oscar, que empiece el espectaculo","2008"),
new Project("Biography","2000-2007"),
new Project("Quelli che... il calcio","2007"),
new Project("Paris Hilton Inc.: The Selling of Celebrity","2007"),
new Project("Shownieuws","2007"),
new Project("The Colbert Report","2007"),
new Project("Fernsehkritik TV","2007"),
new Project("51 premis Sant Jordi de cinematografia","2007"),
new Project("The 79th Annual Academy Awards","2007"),
new Project("Penelope, camino a los Oscar","2007"),
new Project("Canada A.M.","2007"),
new Project("Amor mio","2007"),
new Project("Kig Ind TV","2007"),
new Project("The Fame Review 2006","2006"),
new Project("Headlines on Trial","2006"),
new Project("Headline News","2006"),
new Project("Getaway","2005-2006"),
new Project("Cannes 2006: Cronica de Carlos Boyero","2006"),
new Project("Boffo! Tinseltown's Bombs and Blockbusters","2006"),
new Project("Saturday Night Live: The Best of Saturday TV Funhouse","2006"),
new Project("Corazon de...","2005-2006"),
new Project("The Big Fat Quiz of the Year","2005"),
new Project("Stars on Trial","2005"),
new Project("101 Sexiest Celebrity Bodies","2005"),
new Project("The Oprah Winfrey Show","2005"),
new Project("Cinema mil","2005"),
new Project("Celebrities Uncensored","2003-2004"),
new Project("101 Biggest Celebrity Oops","2004"),
new Project("It's Good to Be...","2003"),
new Project("The Another World Reunion","2003"),
new Project("Shirtless: Hollywood's Sexiest Men","2002"),
new Project("Ultimate Fights from the Movies","2002"),
new Project("E! True Hollywood Story","2002"),
new Project("Gomorron","2002"),
new Project("Interview With the Vampire: In the Shadow of the Vampire","2001"),
new Project("American Arts & Culture Presents John Horatio Malkovich 'Dance of Despair & Disillusionment'","2000"),
new Project("Hollywood Couples","2000"),
new Project("Split Screen","1999"),
new Project("Celebrity First Loves","1995"),
new Project("Weddings of a Lifetime","1995"),
new Project("Joe Bob's Drive-In Theater","1995")])];

//~ echo json_encode($contacts);
$search = "";
if(isset($_GET["search"])){
	$search = $_GET["search"];
}
if(isset($_POST["search"])){
	$search = $_POST["search"];
}
$output = array();
foreach($contacts as $key => $c){
	if(stripos($c->fullname,$search) !== false || stripos($c->nickname,$search) !== false || $search === ""){
		array_push($output, $c);
	}
}
$json = json_encode($output);
echo $json;
?>